name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘‰ Checkout ğŸ‘ˆ
        uses: actions/checkout@v2.3.1

      - name: ğŸ‘€ Installing Dependencies ğŸ‘€
        run: yarn

      - name: ğŸ‘Œ Build project ğŸ‘Œ
        run: yarn build
        
      - name: ğŸ¤ Running tests ğŸ¤
        run: yarn test
          
      - name: â˜• â˜• â˜• Deploy â˜• â˜• â˜•
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
